# Generated by Django 4.2.7 on 2024-04-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='pastquestion',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='report',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='teachermaterial',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='institution',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
