# Generated by Django 4.2.7 on 2024-04-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_book_institution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='count',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='count',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='count',
        ),
        migrations.RemoveField(
            model_name='pastquestion',
            name='count',
        ),
        migrations.RemoveField(
            model_name='report',
            name='count',
        ),
        migrations.RemoveField(
            model_name='teachermaterial',
            name='count',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='count',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='special_id',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='count',
        ),
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='journal',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='journal',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pastquestion',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='report',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='report',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='teachermaterial',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='teachermaterial',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teachermaterial',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='textbook',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='cover',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='publisher',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='pastquestion',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='teachermaterial',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
