# Generated by Django 4.2.7 on 2024-04-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_book_cover_alter_dissertation_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pastquestion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='report',
            name='category',
        ),
        migrations.RemoveField(
            model_name='teachermaterial',
            name='category',
        ),
        migrations.RemoveField(
            model_name='textbook',
            name='category',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='category',
        ),
    ]
