# Generated by Django 4.2.8 on 2024-04-12 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_messagethread_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagethread',
            options={'ordering': ['timestamp']},
        ),
    ]
