# Generated by Django 4.2.8 on 2024-04-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_messagethread_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadreply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
