# Generated by Django 4.2.8 on 2024-04-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_threadreply_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadreply',
            name='key',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='threadreply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
